// Offline-first service worker. The precache list and cache version live in
// sw-precache.js, regenerated by tools/gen_sw.py (locally or in CI) whenever
// app files change. Browsers include importScripts resources in the update
// check, so a new sw-precache.js alone triggers a new install.
importScripts("./sw-precache.js");

const CACHE = "vrtti-" + self.__PRECACHE.version;

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(self.__PRECACHE.files))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  if (new URL(req.url).origin !== location.origin) return;

  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      // A navigation that missed the cache (e.g. a deep link) still gets the
      // app shell, so the installed app opens with no network.
      if (req.mode === "navigate") {
        return caches.match("./index.html").then((shell) => shell || fetch(req));
      }
      return fetch(req);
    })
  );
});
