// Offline-first service worker. The precache list and cache version live in
// sw-precache.js, regenerated by tools/gen_sw.py (locally or in CI) whenever
// app files change. Browsers include importScripts resources in the update
// check, so a new sw-precache.js alone triggers a new install.
importScripts("./sw-precache.js");

const CACHE = "vrtti-" + self.__PRECACHE.version;

// The ~4,000 Twemoji SVGs are not precached (tools/gen_sw.py skips them); they
// are cached one by one on first use. Their cache name is deliberately fixed
// and separate from CACHE: the activate handler deletes every other cache on
// each new build, and an emoji SVG never changes, so re-downloading the set
// after every deploy would be waste.
const EMOJI_CACHE = "vrtti-emoji";
const EMOJI_PATH = "/vendor/twemoji/";

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(self.__PRECACHE.files))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((k) => k !== CACHE && k !== EMOJI_CACHE)
            .map((k) => caches.delete(k))
        )
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  event.respondWith(
    // caches.match without a cache name searches every cache, so an already
    // seen emoji is served from EMOJI_CACHE here.
    caches.match(req, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      // First sighting of this emoji: fetch it and keep it, so it works
      // offline from now on.
      if (url.pathname.includes(EMOJI_PATH)) {
        return fetch(req).then((res) => {
          if (res.ok) {
            const copy = res.clone();
            // waitUntil, or the worker may stop before the write lands.
            event.waitUntil(
              caches.open(EMOJI_CACHE).then((cache) => cache.put(req, copy))
            );
          }
          return res;
        });
      }
      // A navigation that missed the cache (e.g. a deep link) still gets the
      // app shell, so the installed app opens with no network.
      if (req.mode === "navigate") {
        return caches.match("./index.html").then((shell) => shell || fetch(req));
      }
      return fetch(req);
    })
  );
});
