#!/usr/bin/env python3
"""Regenerate the build artifacts: js/version.js and sw-precache.js.

js/version.js is the build stamp the status bar shows, so the user can tell
which build the installed PWA is running. In CI the commit comes from
GITHUB_SHA (the pushed commit). Locally `git rev-parse` gives the *previous*
commit when run before committing; that is fine, CI restamps on deploy.

sw-precache.js is the service worker's file list + cache version. The version
is a content hash over every precached file, so any byte change produces a new
cache name and triggers a service worker update.

Run from anywhere; paths are anchored to this file's location.
"""

import hashlib
import json
import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path

APP = Path(__file__).resolve().parent.parent

# Not precached: dev tooling and docs are still served, but the offline app
# does not need them. sw.js and sw-precache.js are handled by the SW lifecycle
# itself and must not be inside their own cache.
EXCLUDE_DIRS = {"tools"}
EXCLUDE_FILES = {"sw.js", "sw-precache.js", "screenshot.png", "VENDOR.md"}

# Also not precached: the ~4,000 Twemoji SVGs. Precaching them would turn every
# install into an 11 MB, 4,000-request download for emoji the user may never
# type. sw.js caches each one on first use instead, in cache "vrtti-emoji".
EXCLUDE_TREES = ("vendor/twemoji",)


def build_stamp():
    sha = os.environ.get("GITHUB_SHA", "")[:7]
    if not sha:
        try:
            sha = subprocess.run(
                ["git", "rev-parse", "--short", "HEAD"],
                cwd=APP,
                capture_output=True,
                text=True,
                check=True,
            ).stdout.strip()
        except Exception:
            sha = "local"
    built_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return {"commit": sha, "builtAt": built_at}


def write_version(stamp):
    body = (
        "// Generated by tools/gen_sw.py. Do not edit.\n"
        "export const BUILD = " + json.dumps(stamp, indent=2) + ";\n"
    )
    (APP / "js" / "version.js").write_text(body)


def is_excluded(rel):
    if rel.parts[0] in EXCLUDE_DIRS or rel.name in EXCLUDE_FILES:
        return True
    posix = rel.as_posix()
    return any(posix.startswith(tree + "/") for tree in EXCLUDE_TREES)


def precache_files():
    files = []
    for path in sorted(APP.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(APP)
        if is_excluded(rel):
            continue
        files.append(rel)
    return files


def main():
    # Stamp first: version.js must be in the precache list AND in the digest.
    # The timestamp makes every run produce a new cache version; that is
    # deliberate, or an unchanged cache name would serve a stale version.js.
    stamp = build_stamp()
    write_version(stamp)

    files = precache_files()
    digest = hashlib.sha256()
    for rel in files:
        digest.update(str(rel).encode())
        digest.update((APP / rel).read_bytes())
    version = digest.hexdigest()[:12]

    # "./" first: it is the URL a navigation to the scope root actually uses.
    urls = ["./"] + ["./" + rel.as_posix() for rel in files]
    body = "self.__PRECACHE = " + json.dumps(
        {"version": version, "files": urls}, indent=2
    ) + ";\n"
    (APP / "sw-precache.js").write_text(body)
    print(f"version.js: {stamp['commit']} {stamp['builtAt']}")
    print(f"sw-precache.js: {len(urls)} URLs, version {version}")


if __name__ == "__main__":
    main()
